config/routes.rb
Rails.application.routes.draw do
  resources :welcomes
  resources :experiences
  resources :maps
  resources :characters
  resources :users

  get '/login' => 'sessions#new'
  post 'sessions' => 'sessions#create'
  get '/logout' => 'sessions#destroy'

   root 'welcome#welcome'

end

app/models/character.rb
class Character < ActiveRecord::Base
  belongs_to :user
  has_one :map
  has_many :moments, through: :maps
  has_many :maps

end

app/models/experience.rb
class Experience < ActiveRecord::Base
belongs_to :character
attr_accesible :address, :latitude, :longitude
geocoded_by :address
after_validation :geocode, :if => :address_changed
end

app/models/map.rb
class Map < ActiveRecord::Base
has_many :experiences

end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :characters
  has_many :maps, through: :characters
  has_many :experiences, through: :maps

  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :login_required

  private

    def login_required
      if !logged_in?
        redirect_to login_path, :notice => "You need to login"
      end
    end

    def logged_in?
      !!current_user
    end
    helper_method :logged_in?

    def current_user
      @current_user ||= User.find(session[:user_id]) if session[:user_id]
    end
    helper_method :current_user
end

app/controllers/characters_controller.rb
class CharactersController < ApplicationController
  
end

app/controllers/concerns/sessions_controller.rb
sessions_controller.rb

app/controllers/experiences_controller.rb
class ExperiencesController < ApplicationController
end

app/controllers/maps_controller.rb
class MapsController < ApplicationController
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :login_required, :only => [:new, :create]

  def new
  end

  def create
    @user = User.find_by(:email => params[:email])
    if @user && @user.authenticate(params[:password])
      login(@user)
      flash[:notice] = "Logged in successfully"
      redirect_to user_path(current_user.id)
    else
      flash.now[:notice] = "Can't find that user."
      render :new
    end
  end

  def destroy
    reset_session
    redirect_to root_path
  end

  def index

  end

  private
  def login(user)
    session[:user_id] = user.id
  end 
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :login_required

  def new
    @user = User.new
  end

  def create
    @user=User.new(user_params)

    if @user.save
      redirect_to login_path, :notice => "Now please login"
    else
      render :new
    end
  end

  def show
    @user = User.find_by(params[:id])
  end

  private
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  skip_before_action :require_login, only: [:welcome]

  def welcome
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/characters_helper.rb
module CharactersHelper
end

app/helpers/experiences_helper.rb
module ExperiencesHelper
end

app/helpers/maps_helper.rb
module MapsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CharacterMapping</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<nav>
  <% if logged_in? %>
    <%= link_to "Character Profile", user_path(current_user) %> | 
    <%=  link_to "Logout", logout_path %>
  <% else %>
    <%= link_to "Login", login_path %> |
    <%= link_to "Sign Up", new_user_path %>
  <% end %>
</nav>

<p>
<% if flash[:notice] %>
 <%= flash[:notice] %>
<% end %>

  <%= yield %> 
</p>
</body>
</html>

app/views/users/new.html.erb
<%= form_for(@user) do |f| %>
  <p>
    <%= f.label :name %> 
    <%= f.text_field :name %>
  </p>

  <p>
    <%= f.label :email %>
    <%= f.text_field :email %>
  </p>

  <p>
    <%= f.label :password %>
    <%= f.password_field :password %>
  </p>

  <p>
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation %>
  </p>

  <%= f.submit %>

  <% end %>

app/views/users/show.html.erb
<h1>Hi <%= @user.name %></h1>

<h3>Characters:</h3>
<ul>
  <% @user.characters.each do |character| %>
    <li><%= link_to character.name, character_path(character) %></li>
  <% end %>
</ul>

<p>Create a New Character</p>
<%= form_tag("/characters") do %>
  <%= label_tag('character[name]', "Name") %>
  <%= text_field_tag('map[name]') %><br>
  <%= label_tag('map[address]', "Starting Address") %>
  <%= text_field_tag('map[address]')%><br><br>
<%= submit_tag "Create Map", :id => "createcharacter" %>
<% end %>

app/views/welcome/welcome.html.erb
<h1>Welcome</h1>